# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 11:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yourFinance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stashNames', models.TextField(default='Bank account\nSavings\nWallet\nOthers\n')),
                ('costNames', models.TextField(default='Rent and other charges\nTransportation\nClothes\nFood\nHobby\nOthers\n')),
                ('existenceLevel', models.DecimalField(decimal_places=2, default=1500.0, max_digits=8, verbose_name='Existence level monthly cost')),
                ('minimalLevel', models.DecimalField(decimal_places=2, default=2000.0, max_digits=8, verbose_name='Minimal level monthly cost')),
                ('standardLevel', models.DecimalField(decimal_places=2, default=3000.0, max_digits=8, verbose_name='Standard level monthly cost')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
