# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yourFinance', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='year',
            old_name='amount',
            new_name='number',
        ),
    ]
