# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourFinance', '0003_auto_20170424_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='name',
            field=models.CharField(choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sept', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], max_length=10, verbose_name='Month name'),
        ),
        migrations.AlterField(
            model_name='stash',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Money deposition place'),
        ),
        migrations.AlterField(
            model_name='year',
            name='number',
            field=models.DecimalField(decimal_places=0, max_digits=4, verbose_name='Year number'),
        ),
    ]
