# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourFinance', '0004_auto_20170424_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='number',
            field=models.DecimalField(decimal_places=0, max_digits=4, verbose_name='Year'),
        ),
    ]
