# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourFinance', '0006_auto_20170426_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='name',
            field=models.CharField(choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sept', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], max_length=10, verbose_name='Month name'),
        ),
    ]
